Repository teamDry/dry-website, pull requests merged in 2023-08, with the labels that each got.

#1 #1 - 개발환경 세팅
  HELP.md
  build.gradle
  dry-website.iml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/dry/DryWebsiteApplication.java
  src/main/resources/application.properties
  src/test/java/org/dry/DryWebsiteApplicationTests.java
Labels: enhancement

#2 #2 - ERD 1차 작성
  document/ERD.mwb
  document/ERD.svg
Labels: documentation

#5 Member Entity 생성
  build.gradle
  src/main/java/org/dry/config/JpaConfig.java
  src/main/java/org/dry/entity/Member.java
  src/main/java/org/dry/repository/MemberRepository.java
  src/main/resources/application.properties
  src/main/resources/application.yaml
  src/main/resources/data.sql
  src/test/java/org/dry/repository/MemberRepositoryTest.java
Labels: enhancement

#9 mybatis 기능 구현
  build.gradle
  src/main/java/org/dry/DryWebsiteApplication.java
  src/main/java/org/dry/mapper/MemberIdAndPassword.java
  src/main/java/org/dry/mapper/MemberMapper.java
  src/main/resources/application.yaml
  src/main/resources/mappers/memberMapper.xml
  src/test/java/org/dry/mapper/MemberMapperTest.java
Labels: enhancement

#11 23/08/10 코드 수정
  build.gradle
  src/main/java/org/dry/DryWebsiteApplication.java
  src/main/java/org/dry/entity/Member.java
  src/main/java/org/dry/mapper/MemberMapper.java
  src/main/java/org/dry/util/TestUtil.java
  src/main/java/org/dry/vo/MemberIdAndPassword.java
  src/main/resources/application.yaml
  src/main/resources/data.sql
  src/main/resources/mappers/memberMapper.xml
  src/test/java/org/dry/DryWebsiteApplicationTests.java
  src/test/java/org/dry/mapper/MemberMapperTest.java
  src/test/java/org/dry/repository/MemberRepositoryTest.java
Labels: fix

#17 Admin Entity 작성
  src/main/java/org/dry/entity/Admin.java
  src/main/java/org/dry/mapper/AdminMapper.java
  src/main/java/org/dry/repository/AdminRepository.java
  src/main/java/org/dry/util/TestUtil.java
  src/main/resources/data.sql
  src/main/resources/mappers/AdminMapper.xml
  src/test/java/org/dry/mapper/AdminMapperTest.java
  src/test/java/org/dry/repository/AdminRepositoryTest.java
Labels: enhancement

#18 #0 - 클래스 이름 변경
  src/main/java/org/dry/mapper/AdminMapper.java
  src/main/java/org/dry/mapper/MemberMapper.java
  src/main/java/org/dry/vo/IdAndPassword.java
  src/main/resources/mappers/AdminMapper.xml
  src/main/resources/mappers/memberMapper.xml
  src/test/java/org/dry/mapper/AdminMapperTest.java
  src/test/java/org/dry/mapper/MemberMapperTest.java
Labels: fix

#20 Service 구현 및 테스트 작성
  src/main/java/org/dry/service/AdminService.java
  src/main/java/org/dry/service/AdminServiceImpl.java
  src/test/java/org/dry/service/AdminServiceTest.java
Labels: enhancement

#23 #22 - Member Service 및 테스트 작성
  src/main/java/org/dry/service/MemberService.java
  src/main/java/org/dry/service/MemberServiceImpl.java
  src/test/java/org/dry/service/MemberServiceTest.java
Labels: enhancement

#25 Admin Controller 구현
  build.gradle
  src/main/java/org/dry/controller/AdminRestController.java
  src/main/java/org/dry/controller/AdminViewController.java
  src/main/java/org/dry/repository/AdminRepository.java
  src/main/java/org/dry/vo/IdAndPassword.java
  src/main/resources/templates/admin/index.html
  src/main/resources/templates/admin/login.html
  src/main/resources/templates/error/admin-login-failed.html
  src/test/java/org/dry/controller/AdminRestControllerTest.java
  src/test/java/org/dry/controller/AdminViewControllerTest.java
Labels: enhancement

#31 #0 - login.js, sign-up.js 기능 추가 및 코드 수정
  src/main/resources/static/admin/login.js
  src/main/resources/static/admin/sign-up.js
Labels: fix

#32 이메일 인증 기능 구현
  build.gradle
  src/main/java/org/dry/controller/AdminRestController.java
  src/main/java/org/dry/controller/AdminViewController.java
  src/main/java/org/dry/service/EmailService.java
  src/main/java/org/dry/service/EmailServiceImpl.java
  src/main/java/org/dry/service/InviteCodesService.java
  src/main/java/org/dry/service/InviteCodesServiceImpl.java
  src/main/java/org/dry/util/Util.java
  src/main/java/org/dry/vo/IdAndPassword.java
  src/main/resources/application.yaml
  src/main/resources/properties/emailTemplate.properties
  src/main/resources/static/admin/index.js
  src/main/resources/static/admin/login.js
  src/main/resources/static/admin/sign-up.js
  src/main/resources/templates/admin/index.html
  src/test/java/org/dry/controller/AdminRestControllerTest.java
  src/test/java/org/dry/service/EmailServiceImplTest.java
Labels: enhancement

#34 관리자 메인 페이지 뷰 구현
  src/main/java/org/dry/controller/AdminViewController.java
  src/main/resources/static/admin/css/index.css
  src/main/resources/static/admin/index.js
  src/main/resources/static/admin/js/index.js
  src/main/resources/static/admin/js/login.js
  src/main/resources/static/admin/js/sign-up.js
  src/main/resources/static/reset.css
  src/main/resources/templates/admin/index.html
  src/main/resources/templates/admin/login.html
  src/main/resources/templates/admin/sign-up.html
  src/test/java/org/dry/controller/AdminRestControllerTest.java
Labels: enhancement

#36 로그인 뷰 구현
  src/main/resources/static/admin/css/login.css
  src/main/resources/static/admin/js/login.js
  src/main/resources/static/reset.css
  src/main/resources/templates/admin/login.html
Labels: enhancement

#38 회원가입 뷰 구현
  src/main/resources/static/admin/css/sign-up.css
  src/main/resources/static/admin/js/sign-up.js
  src/main/resources/templates/admin/sign-up.html
Labels: enhancement

#41 react 개발 환경 구축
  src/main/java/org/dry/config/WebConfig.java
Labels: enhancement
